### PR TITLE
Change-to-github-api

### PR DESCRIPTION
**Pull request by SenexCrenshaw**

### CODE REVIEW

**Comment by cnorton-dev** [comment]
@SenexCrenshaw nice, I wasn't aware you could use the GitHub API without a token to list all the files in a repository, but that makes it much cleaner and easier to iterate over. 👍🏼

**Comment by cnorton-dev** [comment]
In regards to:

> Excellent! I have a few suggestions
> 
> 1. An option to prefer M3U logos if they are set
> 2. Logo URL in the interface. Wasn't obvious I could remove the existing text and type to complete. It works great, just didn't seem obvious. Maybe note "Logo URL: URL or type to search" ... something like that
> 3. The ability to search by country. Maybe a pull down list of countries at the top of the mapping page which would be added to the autocomplete filter
> 4. The logo json creator is slow. I had another PR I was playing with that downloads using the GitHub API. Maybe you can incorporate this:
>    [logo.go](https://github.com/SenexCrenshaw/xTeVe/blob/logos/src/logo.go)
> 5. func ignoredFiles. I think this can be cleaned up as well
> 6. Maybe a filter in the mapping page for missing Logos only?
> 
> Thanks for a great PR. Let me know your thoughts.

Sounds good, will look into getting these implemented, thanks for the feedback.

**Comment by SenexCrenshaw** [comment]
I am just about done those few items above. You can check out the PR to see where it is going

**Comment by SenexCrenshaw** [comment]
Should be good to go now
[/releases/v.2.5.2](https://github.com/SenexCrenshaw/xTeVe/releases/tag/v2.5.2)

**Pull request merged**
