### PR TITLE
Add support for searching Tapiosinn's tv-logos repository, fix panic error for memory buffer on Windows, default channel logo, login page fix

### PR DESCRIPTION
**Pull request by cnorton-dev**
Fixed a bug with memory buffer option and Windows, if the cache location path is not on the C: volume the virtual file system would cause a panic error as the volume did not exist in the VFS. Fixed by checking if we are on Windows and if the path is located on a volume other than C: we create the volume it is located on in the VFS thus allowing the cache location to properly be created and used in the VFS.

Fixed HostIP and HostName not applying when creating the m3u and xepg files. It now correctly will use either the set HostIP or if HostName is not blank it will override the set HostIP with HostName.

Added the ability to search Tapiosinn's tv-logo repository and easily select a TV channel logo to use from the list.

Added the ability to shift channels in the mapping. On by default in the mapping page, this will allow you to move a channel to an already occupied channel number, shifting the existing channel and all channels after up by 1 number until an empty channel number is found or the end of the channel list is reached. Unchecking the "Shift channels" checkbox returns the mapping page to the old behavior of moving the channel to the next available empty channel number.

Added the ability to preview a TV channel logo URL so when selecting an image from the list or pasting one in it will show a preview of the image or when the channel editing popup is initially open it will preview the current logo URL.

Added a default TV channel logo to be used if the entry is blank. TODO: automatically fill this in when processing EPG?

Added 2 scripts one for PowerShell and one for bash to easily generate the webUI.go file from the html folder for development.

Fix for the login page so you don't have to click on the button to login, you can now press enter in the form.

### CODE REVIEW

**Comment by cnorton-dev** [comment]
@SenexCrenshaw These are the latest features and fixes I have from my development branch including the feature discussed for the channel logo search as well as a big fix for memory buffer on Windows. My fork is now based off yours.

**Comment by SenexCrenshaw** [comment]
Excellent! I have a few suggestions

1. An option to prefer M3U logos if they are set
2. Logo URL in the interface. Wasn't obvious I could remove the existing text and type to complete. It works great, just didn't seem obvious. Maybe note "Logo URL: URL or type to search" ... something like that
3. The ability to search by country. Maybe a pull down list of countries at the top of the mapping page which would be added to the autocomplete filter
4. The logo json creator is slow. I had another PR I was playing with that downloads using the GitHub API. Maybe you can incorporate this:
[logo.go](https://github.com/SenexCrenshaw/xTeVe/blob/logos/src/logo.go)
5. func ignoredFiles. I think this can be cleaned up as well
6. Maybe a filter in the mapping page for missing Logos only?

Thanks for a great PR. Let me know your thoughts.

**Comment by SenexCrenshaw** [comment]
Check out #19 

I converted to the github api for speed.

**Comment by SenexCrenshaw** [comment]
It will be easy to pull the countries out too for the sort filter

**Comment by cnorton-dev** [comment]
@SenexCrenshaw Yes, looks really good! If I had known you could use the GitHub API that way without a key that would have been the way I went and parsed it out like you have, but learned something new about the GitHub API today.

**Comment by cnorton-dev** [comment]
Closing this PR, in reference to #19

**Pull request closed without merging**
